import {
  ArrowRight, Info, Keyboard, Layers, ListChecks, Map as MapIcon, ShieldCheck, Sparkles, Timer, TriangleAlert,
  MapPin, Clock, Route, BrainCircuit, AlertTriangle,
} from 'lucide-react';
import { useStore } from '../store/useStore';
import { DemoTag, PageHeader, Panel } from '../components/common/ui';
import { SEEDS } from '../data/engine';

const STEPS = [
  {
    icon: ListChecks,
    title: '1. Detect',
    body: 'The model compares each forecast field against a 30-year climatology and flags grid cells that behave unusually. An autoencoder catches patterns a plain z-score misses.',
  },
  {
    icon: Layers,
    title: '2. Identify',
    body: 'Flagged cells are clustered into discrete event objects with a centre, an area, a peak value and a detection time.',
  },
  {
    icon: MapIcon,
    title: '3. Track',
    body: 'Across forecast steps, event objects are linked into persistent tracks using Hungarian assignment and a Kalman filter, so you can follow one storm rather than a smear of cells.',
  },
  {
    icon: Sparkles,
    title: '4. Predict',
    body: 'A ConvLSTM forecasts how intensity and footprint evolve; a regression model estimates when the event reaches each downstream region.',
  },
  {
    icon: ShieldCheck,
    title: '5. Alert',
    body: 'Events crossing severity and confidence thresholds are turned into ranked alerts with an estimated arrival time per region.',
  },
];

export function AboutPage() {
  const startOnboarding = useStore((s) => s.startOnboarding);
  const setView = useStore((s) => s.setView);

  return (
    <div className="mx-auto max-w-[1080px] px-4 py-5 sm:px-6">
      <PageHeader
        title="About SIH26078"
        sub="AI-driven tracking of extreme weather anomalies in medium-range forecasts — Smart India Hackathon 2026."
        right={<DemoTag />}
      />

      {/* honesty first */}
      <section className="card mb-4 border-amber-500/30 bg-amber-500/6 p-4">
        <h2 className="flex items-center gap-2 text-[14px] font-semibold text-amber-200">
          <TriangleAlert size={16} /> This is a demonstration, not a forecast
        </h2>
        <p className="mt-1.5 text-[12.5px] leading-relaxed text-txt-mid">
          SIHTRACK is <strong>not connected to IMD, NCMRWF, ECMWF or any operational weather system</strong>. All{' '}
          {SEEDS.length} events, every track, arrival time, statistic and alert on this platform are generated by a deterministic
          in-browser demonstration engine. Positions and arrival times are <strong>AI-based estimates</strong> and must not be used
          for any real decision.
        </p>
      </section>

      {/* how to read the app */}
      <Panel title="How to read this application in 30 seconds" className="mb-4">
        <ol className="divide-y divide-[color:var(--hairline)]">
          {[
            ['What is happening?', 'Look at the map. Every marker is one detected extreme anomaly event.', MapPin],
            ['Where is it?', 'Hover a marker to see the region, intensity, and its severity class.', MapIcon],
            ['How serious is it?', 'Marker colour and the legend: Green (Normal) to Red (Extreme).', AlertTriangle],
            ['Where is it going?', 'Press “Track This Event” — the dashed line is the AI-estimated forecast.', Route],
            ['When will it arrive?', 'The drawer lists each region with its estimated arrival (ETA).', Clock],
            ['How confident is it?', 'Model confidence degrades as the forecast horizon extends to +72h.', ShieldCheck],
            ['How has it changed?', 'Drag the timeline slider under the map to inspect past and future steps.', Timer],
            ['Why does it matter?', 'Read the AI analysis section in the event drawer for synoptic drivers.', BrainCircuit],
          ].map(([q, a, IconComp]) => {
            const Icon = IconComp as any;
            return (
              <li key={q as string} className="flex items-start gap-3 px-4 py-2.5">
                <span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded bg-ink-800 text-brand-300" aria-hidden>
                  <Icon size={13} />
                </span>
                <span className="min-w-0">
                  <span className="block text-[13px] font-semibold text-txt-hi">{q as string}</span>
                  <span className="block text-[12px] text-txt-lo">{a as string}</span>
                </span>
              </li>
            );
          })}
        </ol>
        <div className="border-t border-edge px-4 py-3">
          <button className="btn !py-2 text-[12.5px]" onClick={startOnboarding}>
            <Info size={13} /> Show the 3-step guide
          </button>
          <button className="btn ml-2 !py-2 text-[12.5px]" onClick={() => setView('map')}>
            Open the map <ArrowRight size={13} />
          </button>
        </div>
      </Panel>

      {/* the pipeline */}
      <Panel title="How the model works" sub="From raw forecast field to a tracked, predicted event" className="mb-4">
        <ol className="space-y-2 p-4">
          {STEPS.map((s) => {
            const I = s.icon;
            return (
              <li key={s.title} className="flex items-start gap-3 rounded-lg border border-edge bg-ink-900/60 px-3 py-2.5">
                <span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg border border-brand-500/40 bg-brand-500/10 text-brand-300">
                  <I size={15} />
                </span>
                <span className="min-w-0">
                  <span className="block text-[13px] font-semibold text-txt-hi">{s.title}</span>
                  <span className="block text-[12px] leading-relaxed text-txt-mid">{s.body}</span>
                </span>
              </li>
            );
          })}
        </ol>
      </Panel>

      {/* data on screen */}
      <Panel title="What you are looking at" className="mb-4">
        <div className="grid gap-3 p-4 sm:grid-cols-2">
          <div>
            <h3 className="text-[12.5px] font-semibold text-txt-hi">Severity classes</h3>
            <ul className="mt-1.5 space-y-1">
              {[
                ['● Extreme', 'Composite score 82 and above', '#ef4444'],
                ['▲ High', 'Composite score 68 to 81', '#f97316'],
                ['■ Moderate', 'Composite score 55 to 67', '#eab308'],
                ['✓ Normal', 'Below the detection threshold', '#22c55e'],
              ].map(([label, desc, color]) => (
                <li key={label} className="flex items-baseline gap-2 text-[12px]">
                  <span className="w-[92px] shrink-0 font-semibold" style={{ color }}>
                    {label}
                  </span>
                  <span className="text-txt-lo">{desc}</span>
                </li>
              ))}
            </ul>
            <p className="mt-2 text-[11.5px] leading-relaxed text-txt-lo">
              The composite score blends how intense the event is with how unusual it is for that place and time of year.
            </p>
          </div>
          <div>
            <h3 className="text-[12.5px] font-semibold text-txt-hi">Map symbology</h3>
            <ul className="mt-1.5 space-y-1.5">
              <li className="flex items-center gap-2 text-[12px] text-txt-mid">
                <svg width="26" height="6" aria-hidden>
                  <line x1="0" y1="3" x2="26" y2="3" stroke="#7dd3fc" strokeWidth="2.5" strokeLinecap="round" />
                </svg>
                Solid line — where the event <strong className="text-txt-hi">has been</strong>
              </li>
              <li className="flex items-center gap-2 text-[12px] text-txt-mid">
                <span className="h-2.5 w-2.5 rounded-full border-2 border-sky-300" aria-hidden />
                Large marker — <strong className="text-txt-hi">where it is now</strong>
              </li>
              <li className="flex items-center gap-2 text-[12px] text-txt-mid">
                <svg width="26" height="6" aria-hidden>
                  <line x1="0" y1="3" x2="26" y2="3" stroke="#a78bfa" strokeWidth="2.5" strokeDasharray="4 3" strokeLinecap="round" />
                </svg>
                Dashed line — <strong className="text-txt-hi">where it is expected to go</strong>
              </li>
              <li className="flex items-center gap-2 text-[12px] text-txt-mid">
                <span className="h-2.5 w-7 rounded-sm border border-dashed border-sky-300/50 bg-sky-400/15" aria-hidden />
                Shaded band — <strong className="text-txt-hi">how uncertain that is</strong>
              </li>
            </ul>
            <p className="mt-2 text-[11.5px] leading-relaxed text-txt-lo">
              The band widens with time because the further ahead you look, the less certain the model is.
            </p>
          </div>
        </div>
      </Panel>

      {/* keyboard + tech */}
      <div className="grid gap-3 sm:grid-cols-2">
        <Panel title="Keyboard shortcuts" icon={<Keyboard size={14} className="text-brand-300" />}>
          <ul className="space-y-1.5 p-4 text-[12px]">
            {[
              ['Space', 'Play / pause the timeline'],
              ['← →', 'Move 6 hours back / forward'],
              ['M / E / A / F', 'Map · Events · Analytics · Forecast'],
              ['L', 'Alerts'],
              ['R', 'Reset the map to the India view'],
              ['Esc', 'Close the event panel'],
            ].map(([k, v]) => (
              <li key={k} className="flex items-center gap-2.5">
                <kbd className="kbd w-[86px] text-center">{k}</kbd>
                <span className="text-txt-lo">{v}</span>
              </li>
            ))}
          </ul>
        </Panel>

        <Panel title="Technical detail" icon={<Timer size={14} className="text-brand-300" />}>
          <div className="space-y-2 p-4 text-[12px] leading-relaxed text-txt-mid">
            <p>
              Built with React, TypeScript, Vite, Tailwind CSS, Zustand and the Google Maps JavaScript API. Recharts handles the
              charts; the basemap is Google's vector rendering, loaded on demand, with weather fields drawn as raster overlays.
            </p>
            <p>
              The demonstration dataset contains <strong className="text-txt-hi">{SEEDS.length} events</strong> spread across India,
              each with a full past track, a forecast track, an uncertainty corridor, per-region arrival times and a confidence
              curve. Every chart and panel reads the same dataset.
            </p>
            <p>
              The intended production stack is FastAPI with PyTorch (ConvLSTM + autoencoder), xarray and PostgreSQL/PostGIS. The
              mock API layer in the source mirrors that surface, so no UI file would need to change.
            </p>
            <p className="text-txt-lo">
              Map data © Google. State boundaries from open India boundary vectors, bundled with the app.
            </p>
          </div>
        </Panel>
      </div>
    </div>
  );
}
